Purpose: Set up a TPM file for WGCNA and, separately, do some basic data exploration.<br>
Author: Anna Pardo

In [1]:
import pandas as pd

In [2]:
tpm = pd.read_csv("../../data/rawtpm_bptreat_noPEG.tsv",sep="\t",header="infer")

In [3]:
tpm.head()

,Sample,BioProject,Treatment,Zm00001eb000010,Zm00001eb000020,Zm00001eb000050,Zm00001eb000060,Zm00001eb000070,Zm00001eb000080,Zm00001eb000100,...,Zm00001eb442810,Zm00001eb442820,Zm00001eb442840,Zm00001eb442850,Zm00001eb442870,Zm00001eb442890,Zm00001eb442910,Zm00001eb442960,Zm00001eb442980,Zm00001eb443030
0,SRR11933261,PRJNA637522,Drought,12.553818,2.321077,0.042520,12.932676,5.253755,11.105837,0.409268,...,0.171184,0.000000,0.0,0.0,0.0,0.309501,0.0,0.000000,0.0,0.000000
1,SRR11933272,PRJNA637522,Drought,16.255838,3.110372,0.405226,7.214039,1.902461,2.346186,0.170305,...,0.108052,0.127878,0.0,0.0,0.0,6.703281,0.0,0.000000,0.0,0.000000
2,SRR11933250,PRJNA637522,Drought,9.028815,2.984479,0.000000,3.092442,2.586555,16.186141,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.417565,0.0,0.254123,0.0,1.213349
3,SRR11933029,PRJNA637522,Control,8.201340,2.385748,0.000000,1.726808,1.926412,19.600487,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.370075
4,SRR11933040,PRJNA637522,Drought,10.371251,2.799099,0.000000,1.280629,3.771234,19.717683,0.143764,...,0.178304,0.012158,0.0,0.0,0.0,9.625225,0.0,0.000000,0.0,2.352959

## Set up the TPM file for WGCNA

In [4]:
## drop BioProject & Treatment columns
tpmd = tpm.drop(["BioProject","Treatment"],axis=1)
tpmd.head()

,Sample,Zm00001eb000010,Zm00001eb000020,Zm00001eb000050,Zm00001eb000060,Zm00001eb000070,Zm00001eb000080,Zm00001eb000100,Zm00001eb000110,Zm00001eb000120,...,Zm00001eb442810,Zm00001eb442820,Zm00001eb442840,Zm00001eb442850,Zm00001eb442870,Zm00001eb442890,Zm00001eb442910,Zm00001eb442960,Zm00001eb442980,Zm00001eb443030
0,SRR11933261,12.553818,2.321077,0.042520,12.932676,5.253755,11.105837,0.409268,0.0,1.122904,...,0.171184,0.000000,0.0,0.0,0.0,0.309501,0.0,0.000000,0.0,0.000000
1,SRR11933272,16.255838,3.110372,0.405226,7.214039,1.902461,2.346186,0.170305,0.0,2.280915,...,0.108052,0.127878,0.0,0.0,0.0,6.703281,0.0,0.000000,0.0,0.000000
2,SRR11933250,9.028815,2.984479,0.000000,3.092442,2.586555,16.186141,0.000000,0.0,1.908468,...,0.000000,0.000000,0.0,0.0,0.0,0.417565,0.0,0.254123,0.0,1.213349
3,SRR11933029,8.201340,2.385748,0.000000,1.726808,1.926412,19.600487,0.000000,0.0,1.619452,...,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.370075
4,SRR11933040,10.371251,2.799099,0.000000,1.280629,3.771234,19.717683,0.143764,0.0,2.264390,...,0.178304,0.012158,0.0,0.0,0.0,9.625225,0.0,0.000000,0.0,2.352959

In [5]:
# transpose data
tpmt = tpmd.set_index("Sample").transpose()
tpmt.head()

Sample,SRR11933261,SRR11933272,SRR11933250,SRR11933029,SRR11933040,SRR11932822,SRR11932811,SRR11933230,SRR11932879,SRR11933475,...,Ms71D3C,Ki3D1C,CML228D1D,CML333D3D,MO18WD3C,B73D3C,NC358D3C,P39D3D,M162WD3D,M162WD1D
Zm00001eb000010,12.553818,16.255838,9.028815,8.201340,10.371251,37.430009,39.925873,30.677016,23.393003,15.222661,...,1.417104,1.923525,1.427602,9.580153,1.228100,2.966207,1.791556,4.286976,3.435711,3.498243
Zm00001eb000020,2.321077,3.110372,2.984479,2.385748,2.799099,27.508819,22.440680,24.648455,7.595576,3.913437,...,0.000000,1.799671,0.000000,0.000000,1.925157,0.561768,0.176413,0.781353,0.379497,0.463832
Zm00001eb000050,0.042520,0.405226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.304751,0.334832,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Zm00001eb000060,12.932676,7.214039,3.092442,1.726808,1.280629,29.510498,22.148225,22.170584,14.727189,13.907885,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Zm00001eb000070,5.253755,1.902461,2.586555,1.926412,3.771234,7.005587,7.590336,5.274585,2.177748,1.810991,...,0.000000,0.451827,0.000000,1.018369,0.000000,0.000000,0.000000,0.000000,1.660372,0.748587

In [6]:
tpmt = tpmt.reset_index().rename(columns={"index":"GeneID"})
tpmt.head()

Sample,GeneID,SRR11933261,SRR11933272,SRR11933250,SRR11933029,SRR11933040,SRR11932822,SRR11932811,SRR11933230,SRR11932879,...,Ms71D3C,Ki3D1C,CML228D1D,CML333D3D,MO18WD3C,B73D3C,NC358D3C,P39D3D,M162WD3D,M162WD1D
0,Zm00001eb000010,12.553818,16.255838,9.028815,8.201340,10.371251,37.430009,39.925873,30.677016,23.393003,...,1.417104,1.923525,1.427602,9.580153,1.228100,2.966207,1.791556,4.286976,3.435711,3.498243
1,Zm00001eb000020,2.321077,3.110372,2.984479,2.385748,2.799099,27.508819,22.440680,24.648455,7.595576,...,0.000000,1.799671,0.000000,0.000000,1.925157,0.561768,0.176413,0.781353,0.379497,0.463832
2,Zm00001eb000050,0.042520,0.405226,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.304751,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,Zm00001eb000060,12.932676,7.214039,3.092442,1.726808,1.280629,29.510498,22.148225,22.170584,14.727189,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,Zm00001eb000070,5.253755,1.902461,2.586555,1.926412,3.771234,7.005587,7.590336,5.274585,2.177748,...,0.000000,0.451827,0.000000,1.018369,0.000000,0.000000,0.000000,0.000000,1.660372,0.748587

In [7]:
tpmt.to_csv("../../data/rawtpm_forWGCNA_noPEG.tsv",sep="\t",header=True,index=False)

In [4]:
# load metadata
md = pd.read_csv("../../data/srr_numbers_with_metadata_12-May-2023.csv",sep=",",header="infer",usecols=["Sample","BioProject","Tissue"])
md.head()

    BioProject       Sample Tissue
0  PRJNA637522  SRR11933261   Leaf
1  PRJNA637522  SRR11933272   Leaf
2  PRJNA637522  SRR11933250   Leaf
3  PRJNA637522  SRR11933029   Leaf
4  PRJNA637522  SRR11933040   Leaf

In [6]:
tpmtissue = md.merge(tpm)
tpmtissue.head()

,BioProject,Sample,Tissue,Treatment,Zm00001eb000010,Zm00001eb000020,Zm00001eb000050,Zm00001eb000060,Zm00001eb000070,Zm00001eb000080,...,Zm00001eb442810,Zm00001eb442820,Zm00001eb442840,Zm00001eb442850,Zm00001eb442870,Zm00001eb442890,Zm00001eb442910,Zm00001eb442960,Zm00001eb442980,Zm00001eb443030
0,PRJNA637522,SRR11933261,Leaf,Drought,12.553818,2.321077,0.042520,12.932676,5.253755,11.105837,...,0.171184,0.000000,0.0,0.0,0.0,0.309501,0.0,0.000000,0.0,0.000000
1,PRJNA637522,SRR11933272,Leaf,Drought,16.255838,3.110372,0.405226,7.214039,1.902461,2.346186,...,0.108052,0.127878,0.0,0.0,0.0,6.703281,0.0,0.000000,0.0,0.000000
2,PRJNA637522,SRR11933250,Leaf,Drought,9.028815,2.984479,0.000000,3.092442,2.586555,16.186141,...,0.000000,0.000000,0.0,0.0,0.0,0.417565,0.0,0.254123,0.0,1.213349
3,PRJNA637522,SRR11933029,Leaf,Control,8.201340,2.385748,0.000000,1.726808,1.926412,19.600487,...,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.370075
4,PRJNA637522,SRR11933040,Leaf,Drought,10.371251,2.799099,0.000000,1.280629,3.771234,19.717683,...,0.178304,0.012158,0.0,0.0,0.0,9.625225,0.0,0.000000,0.0,2.352959

## Data exploration: stressor representation, numbers of BioProjects, etc.

In [7]:
# subset to just leaf tissue and find out if all stressors are represented
tpmtissue[tpmtissue["Tissue"]=="Leaf"]["Treatment"].unique()

array(['Drought', 'Control', 'Heat', 'Cold', 'Salt', 'DroughtRepeat',
       'Low_Nitrogen', 'Flooding'], dtype=object)

In [22]:
leaf = tpmtissue[tpmtissue["Tissue"]=="Leaf"].drop("Tissue",axis=1)

In [23]:
leaf.head()

,BioProject,Sample,Treatment,Zm00001eb000010,Zm00001eb000020,Zm00001eb000050,Zm00001eb000060,Zm00001eb000070,Zm00001eb000080,Zm00001eb000100,...,Zm00001eb442810,Zm00001eb442820,Zm00001eb442840,Zm00001eb442850,Zm00001eb442870,Zm00001eb442890,Zm00001eb442910,Zm00001eb442960,Zm00001eb442980,Zm00001eb443030
0,PRJNA637522,SRR11933261,Drought,12.553818,2.321077,0.042520,12.932676,5.253755,11.105837,0.409268,...,0.171184,0.000000,0.0,0.0,0.0,0.309501,0.0,0.000000,0.0,0.000000
1,PRJNA637522,SRR11933272,Drought,16.255838,3.110372,0.405226,7.214039,1.902461,2.346186,0.170305,...,0.108052,0.127878,0.0,0.0,0.0,6.703281,0.0,0.000000,0.0,0.000000
2,PRJNA637522,SRR11933250,Drought,9.028815,2.984479,0.000000,3.092442,2.586555,16.186141,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.417565,0.0,0.254123,0.0,1.213349
3,PRJNA637522,SRR11933029,Control,8.201340,2.385748,0.000000,1.726808,1.926412,19.600487,0.000000,...,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,1.370075
4,PRJNA637522,SRR11933040,Drought,10.371251,2.799099,0.000000,1.280629,3.771234,19.717683,0.143764,...,0.178304,0.012158,0.0,0.0,0.0,9.625225,0.0,0.000000,0.0,2.352959

In [9]:
# count number of BioProjects for each stressor when including all tissues
for s in ["Drought","Salt","Cold","Heat","Low_Nitrogen","Flooding"]:
    stpm = tpmtissue[tpmtissue["Treatment"]==s]
    print(s)
    print(len(stpm["BioProject"].unique()))

Drought
15
Salt
5
Cold
8
Heat
8
Low_Nitrogen
5
Flooding
3

In [10]:
# now do it again for including only leaf tissue
for s in ["Drought","Salt","Cold","Heat","Low_Nitrogen","Flooding"]:
    stpm = leaf[leaf["Treatment"]==s]
    print(s)
    print(len(stpm["BioProject"].unique()))

Drought
12
Salt
4
Cold
3
Heat
7
Low_Nitrogen
3
Flooding
1

In [11]:
tpmtissue["Tissue"].unique()

array(['Leaf', 'Root', 'Ear', 'Kernel', 'Shoot', 'Tassel', 'Silk',
       'Stalk', 'Pollen', 'Embryo', 'Ovary', 'Leaf meristem'],
      dtype=object)

In [12]:
vegtissues = ["Leaf","Root","Shoot","Stalk","Leaf meristem"]
reptissues = ["Ear","Kernel","Tassel","Silk","Pollen","Embryo","Ovary"]

In [24]:
veg = tpmtissue[tpmtissue["Tissue"].isin(vegtissues)].drop("Tissue",axis=1)
rep = tpmtissue[tpmtissue["Tissue"].isin(reptissues)].drop("Tissue",axis=1)

In [14]:
# count BioProjects per stressor in vegetative tissues
for s in ["Drought","Salt","Cold","Heat","Low_Nitrogen","Flooding"]:
    stpm = veg[veg["Treatment"]==s]
    print(s)
    print(len(stpm["BioProject"].unique()))

Drought
15
Salt
5
Cold
6
Heat
7
Low_Nitrogen
5
Flooding
3

In [15]:
# count BioProjects per stressor in reproductive tissues
for s in ["Drought","Salt","Cold","Heat","Low_Nitrogen","Flooding"]:
    stpm = rep[rep["Treatment"]==s]
    print(s)
    print(len(stpm["BioProject"].unique()))

Drought
3
Salt
0
Cold
2
Heat
2
Low_Nitrogen
0
Flooding
0

In [25]:
# save leaf, veg, and rep
leaf.to_csv("../../data/rawtpm_leafonly.tsv",sep="\t",header=True,index=False)
veg.to_csv("../../data/rawtpm_vegtissues.tsv",sep="\t",header=True,index=False)
rep.to_csv("../../data/rawtpm_reptissues.tsv",sep="\t",header=True,index=False)

In [21]:
t = ["Drought","Cold","Heat"]
with open("../../data/rep_stressors.txt","w+") as outfile:
    for i in t:
        outfile.write(i+"\n")

In [11]:
# find out how many samples for each dataset
for s in ["Drought","Salt","Cold","Heat","Low_Nitrogen","Flooding"]:
    if s=="Drought":
        stpm = tpm[tpm["Treatment"].isin(["Drought","DroughtRepeat"])]
    else:
        stpm = tpm[tpm["Treatment"]==s]
    print("Number of samples for stressor "+s+": "+str(len(stpm["Sample"].unique())))

Number of samples for stressor Drought: 608
Number of samples for stressor Salt: 29
Number of samples for stressor Cold: 225
Number of samples for stressor Heat: 187
Number of samples for stressor Low_Nitrogen: 76
Number of samples for stressor Flooding: 48

In [12]:
for s in ["Drought","Salt","Cold","Heat","Low_Nitrogen","Flooding"]:
    if s=="Drought":
        stpm = tpm[tpm["Treatment"].isin(["Drought","DroughtRepeat"])]
    else:
        stpm = tpm[tpm["Treatment"]==s]
    sbp = stpm["BioProject"].unique()
    sbptpm = tpm[tpm["BioProject"].isin(sbp)]
    sbptpm = sbptpm[sbptpm["Treatment"].isin(["Control",s])]
    print("Number of samples for stressor "+s+" + controls: "+str(len(sbptpm["Sample"].unique())))

Number of samples for stressor Drought + controls: 983
Number of samples for stressor Salt + controls: 56
Number of samples for stressor Cold + controls: 474
Number of samples for stressor Heat + controls: 397
Number of samples for stressor Low_Nitrogen + controls: 149
Number of samples for stressor Flooding + controls: 69

In [9]:
# total number of samples?
print("Total number of samples in dataset: "+str(len(tpm["Sample"].unique())))

Total number of samples in dataset: 1981

In [13]:
nondrought = ["Salt","Cold","Heat","Low_Nitrogen","Flooding"]

In [21]:
with open("../../data/ndstressors.txt","w+") as outfile:
    for i in ["Cold","Heat"]:
        outfile.write(i+"\n")sqs

In [15]:
# subset to just temperature stresses and save a TPM file
bp = []
for s in ["Cold","Heat"]:
    stpm = tpm[tpm["Treatment"]==s]
    for b in stpm["BioProject"].unique():
        bp.append(b)
temp = tpm[tpm["BioProject"].isin(bp)]
temp.head()

,Sample,BioProject,Treatment,Zm00001eb000010,Zm00001eb000020,Zm00001eb000050,Zm00001eb000060,Zm00001eb000070,Zm00001eb000080,Zm00001eb000100,...,Zm00001eb442810,Zm00001eb442820,Zm00001eb442840,Zm00001eb442850,Zm00001eb442870,Zm00001eb442890,Zm00001eb442910,Zm00001eb442960,Zm00001eb442980,Zm00001eb443030
49,SRR8239716,PRJNA506720,Control,13.307581,0.621747,0.705166,12.834716,0.00000,12.535524,0.000000,...,0.000000,0.074918,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
50,SRR8239717,PRJNA506720,Control,12.099089,1.153982,0.427002,12.453924,0.13578,14.098531,0.097319,...,0.000000,0.055655,0.0,0.0,0.000000,2.025144,0.0,0.0,0.0,0.0
51,SRR8239718,PRJNA506720,Control,11.614700,0.888177,0.225754,12.843784,0.00000,13.097301,0.076766,...,0.000000,0.030974,0.0,0.0,0.000000,0.745324,0.0,0.0,0.0,0.0
52,SRR8239725,PRJNA506720,Heat,21.851277,3.355300,0.000000,23.267709,0.13253,33.187876,0.680749,...,0.052413,0.026037,0.0,0.0,0.000000,12.167677,0.0,0.0,0.0,0.0
53,SRR8239726,PRJNA506720,Heat,20.513799,3.770040,0.000000,22.634640,0.00000,28.939382,0.992501,...,0.115351,0.078221,0.0,0.0,0.435959,19.795565,0.0,0.0,0.0,0.0

In [18]:
temp["Treatment"].unique()

array(['Control', 'Heat', 'Cold'], dtype=object)

In [17]:
temp = temp[temp["Treatment"].isin(["Control","Heat","Cold"])]

In [20]:
temp.to_csv("../../data/rawtpm_temperatures.tsv",sep="\t",header=True,index=False)

In [3]:
# subset TPM to non-drought samples
nd = tpm[tpm["Treatment"].isin(["Heat","Cold","Salt","Low_Nitrogen","Flooding"])]["BioProject"].unique()

In [5]:
ndtpm = tpm[tpm["BioProject"].isin(nd)]
ndtpm = ndtpm[~ndtpm["Treatment"].isin(["Drought","DroughtRepeat"])]
ndtpm.head()

,Sample,BioProject,Treatment,Zm00001eb000010,Zm00001eb000020,Zm00001eb000050,Zm00001eb000060,Zm00001eb000070,Zm00001eb000080,Zm00001eb000100,...,Zm00001eb442810,Zm00001eb442820,Zm00001eb442840,Zm00001eb442850,Zm00001eb442870,Zm00001eb442890,Zm00001eb442910,Zm00001eb442960,Zm00001eb442980,Zm00001eb443030
49,SRR8239716,PRJNA506720,Control,13.307581,0.621747,0.705166,12.834716,0.00000,12.535524,0.000000,...,0.000000,0.074918,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
50,SRR8239717,PRJNA506720,Control,12.099089,1.153982,0.427002,12.453924,0.13578,14.098531,0.097319,...,0.000000,0.055655,0.0,0.0,0.000000,2.025144,0.0,0.0,0.0,0.0
51,SRR8239718,PRJNA506720,Control,11.614700,0.888177,0.225754,12.843784,0.00000,13.097301,0.076766,...,0.000000,0.030974,0.0,0.0,0.000000,0.745324,0.0,0.0,0.0,0.0
52,SRR8239725,PRJNA506720,Heat,21.851277,3.355300,0.000000,23.267709,0.13253,33.187876,0.680749,...,0.052413,0.026037,0.0,0.0,0.000000,12.167677,0.0,0.0,0.0,0.0
53,SRR8239726,PRJNA506720,Heat,20.513799,3.770040,0.000000,22.634640,0.00000,28.939382,0.992501,...,0.115351,0.078221,0.0,0.0,0.435959,19.795565,0.0,0.0,0.0,0.0

In [6]:
ndtpm["Treatment"].unique()

array(['Control', 'Heat', 'Cold', 'Salt', 'Low_Nitrogen', 'Flooding'],
      dtype=object)

In [7]:
ndtpm.to_csv("../../data/rawtpm_non_drought.tsv",sep="\t",header=True,index=False)

In [ ]:
# work out code for 5-way balancing, where each stressor is down/upsampled to match the lowest/highest number of samples in the 
## overall dataset
## can use ndtpm as an example dataframe for this

# start by finding the stressors with the lowest and highest number of samples (excluding controls, we'll deal with them later)